### ISSUE TITLE
引入静态资源文件报错

### ISSUE THREAD

**Issue by zhiqingchen** [wuba/taro-react-native#151]
### 使用

```
const { mergeConfig } = require("metro-config");
const path = require('path')
const Supporter = require('@tarojs/rn-supporter')

const supporter = new Supporter()
const taroMetroConfig = supporter.getMetroConfig()

const busConfig = {
  resetCache:true,
  projectRoot: path.resolve(__dirname),
  resolver: {}
}
module.exports = mergeConfig(busConfig,taroMetroConfig)
```

### 报错
```
error: Error: Unable to resolve module ./app.json from /Users/p/Taro-Code-In-React-Native/index.js: ./app.json could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
   5 | import {AppRegistry} from 'react-native';
   6 | import App from './App';
>  7 | import {name as appName} from './app.json';
     |                                ^
   8 |
   9 | AppRegistry.registerComponent(appName, () => App);
  10 |
    at ModuleResolver.resolveDependency (/Users/p/Taro-Code-In-React-Native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:235:15)
    at DependencyGraph.resolveDependency (/Users/p/Taro-Code-In-React-Native/node_modules/metro/src/node-haste/DependencyGraph.js:419:43)
    at Object.resolve (/Users/p/Taro-Code-In-React-Native/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/p/Taro-Code-In-React-Native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/p/Taro-Code-In-React-Native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/p/Taro-Code-In-React-Native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/p/Taro-Code-In-React-Native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/p/Taro-Code-In-React-Native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
```

### 原因

MetroResolver.resolve 参数变更

metro 0.58.0
```
      resolveAsset: (dirPath, assetName, platform) =>

```

metro 0.64.0
```
      resolveAsset: (dirPath, assetName, extension) => {

```

**Comment by zhiqingchen** [comment]
统一更新metro相关依赖致最新版本

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro/pull/9540/commits/10688366e63b0562cbe605e6b046c6ffe7bbbeb6
